"""(tasks): add subtasks with parent-child relationship (3 levels)

Revision ID: 6d57a4a8455a
Revises: 82276e64393e
Create Date: 2025-11-28 21:34:55.311652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d57a4a8455a'
down_revision = '82276e64393e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_task_parent', 'task', ['parent_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('fk_task_parent', type_='foreignkey')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
