"""Ajout colonne priorité

Revision ID: 935d25b93972
Revises: 
Create Date: 2025-11-17 21:33:39.486387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '935d25b93972'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
